In [1]:
import numpy as np

**## Solve Linear system using SVD**

In [2]:
A_system = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 10]], dtype=float)
b_system = np.array([3, 3, 4], dtype=float)

print(f"Matrix A:\n{A_system}")
print(f"Vector b: {b_system}")

# SVD solution: x = V * Σ^(-1) * U^T * b
U_s, s_s, Vt_s = np.linalg.svd(A_system)

# Compute pseudoinverse of Sigma
s_inv = 1.0 / s_s
Sigma_inv = np.diag(s_inv)

# Solve: x = V @ Σ^(-1) @ U.T @ b
x_svd = Vt_s.T @ Sigma_inv @ U_s.T @ b_system

# Direct solution
x_direct = np.linalg.solve(A_system, b_system)

# Verification
residual_svd = np.linalg.norm(A_system @ x_svd - b_system)
residual_direct = np.linalg.norm(A_system @ x_direct - b_system)

print(f"\nSolution using SVD:      {x_svd}")
print(f"Solution using direct:   {x_direct}")
print(f"Difference: {np.linalg.norm(x_svd - x_direct):.2e}")

print(f"\nResidual ||Ax - b|| (SVD):    {residual_svd:.2e}")
print(f"Residual ||Ax - b|| (direct): {residual_direct:.2e}")

# Condition number analysis
cond_number = np.max(s_s) / np.min(s_s)
print(f"\nCondition number of A: {cond_number:.2f}")
print(f"Singular values: {s_s}")

Matrix A:
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. 10.]]
Vector b: [3. 3. 4.]

Solution using SVD:      [-2.  1.  1.]
Solution using direct:   [-2.  1.  1.]
Difference: 1.27e-14

Residual ||Ax - b|| (SVD):    6.89e-15
Residual ||Ax - b|| (direct): 8.88e-16

Condition number of A: 88.45
Singular values: [17.41250517  0.87516135  0.19686652]
