In [1]:
import numpy as np

set random seed for reproducibility

In [2]:
np.random.seed(42)


## Implement SVD

In [3]:
def perform_svd(A):
    """
    Perform Singular Value Decomposition on matrix A.
    Returns U, singular values (vector), and Vt
    """
    U, s, Vt = np.linalg.svd(A, full_matrices=False)
    return U, s, Vt

def reconstruct_from_svd(U, s, Vt):
    """
    Reconstruct original matrix from SVD components.
    """
    Sigma = np.diag(s)
    return U @ Sigma @ Vt

# Test matrix
A_task1 = np.array([[1, 2, 3],
                    [4, 5, 6]], dtype=float)

print(f"Original Matrix A (2x3):\n{A_task1}\n")

U, s, Vt = perform_svd(A_task1)
Sigma = np.diag(s)

print(f"Matrix U ({U.shape}):\n{U}\n")
print(f"Singular Values Σ (vector): {s}")
print(f"Σ as diagonal matrix:\n{Sigma}\n")
print(f"Matrix V^T ({Vt.shape}):\n{Vt}\n")

# Reconstruction
A_reconstructed = reconstruct_from_svd(U, s, Vt)
print(f"Reconstructed Matrix:\n{A_reconstructed}\n")
print(f"Reconstruction Error (Frobenius norm): {np.linalg.norm(A_task1 - A_reconstructed):.2e}")
print(f"Verification: A = UΣV^T? {np.allclose(A_task1, A_reconstructed)}")


Original Matrix A (2x3):
[[1. 2. 3.]
 [4. 5. 6.]]

Matrix U ((2, 2)):
[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]

Singular Values Σ (vector): [9.508032   0.77286964]
Σ as diagonal matrix:
[[9.508032   0.        ]
 [0.         0.77286964]]

Matrix V^T ((2, 3)):
[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]]

Reconstructed Matrix:
[[1. 2. 3.]
 [4. 5. 6.]]

Reconstruction Error (Frobenius norm): 2.75e-15
Verification: A = UΣV^T? True
